apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: bdd
    env:
    - name: MYSQL_ROOT_PASSWORD
      value : password
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: data-volume

  volumes:
    - name: data-volume
      hostPath: 
        path: /data
        type: DirectoryOrCreate
