apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: pv-stock
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 1Gi
  hostPath:
    path : "/data-pv"